server:
  port:8080


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/product_service_db
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database_platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update


